"""empty message

Revision ID: c5c008f8150d
Revises: 4aa73dcab3c1
Create Date: 2024-08-06 14:18:18.361385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c008f8150d'
down_revision = '4aa73dcab3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
